### ISSUE TITLE
Incompatibility with nvd3 library

### ISSUE THREAD

**Issue by alnavart** [chiquitinxx/grooscript#22]
When I include the library js/lib/grooscript.min.js inside the example, this example will be broken.
![captura de pantalla 2015-01-12 a la s 20 10 11](https://cloud.githubusercontent.com/assets/9938624/5709110/4c63aef2-9a97-11e4-87f0-7e291aba1c04.png)

Could be tested if you include:
grooscript.min.js

inside this file:
https://github.com/nvd3-community/nvd3/blob/master/examples/donutChart.html

**Comment by chiquitinxx** [comment]
Alberto, can you please provide the html that fails?. I have tried an example and no error.

Thank you!

**Comment by chiquitinxx** [comment]
I got the error! nvm

**Comment by chiquitinxx** [comment]
Array.prototype.toString() is used by the library, was bad overrided in grooscript

**Comment by alnavart** [comment]
Thank you very much for response and resolution so quick.
I'm starting to use grooscript, it seems very interesting and I hope it will be very useful.
