### ISSUE TITLE
Build tests fails in Java 8

### ISSUE THREAD

**Issue by chiquitinxx** [chiquitinxx/grooscript#24]
In Java 8, javascript engine 'rhino' is replaced by 'nashorn'. Evaluating code with 'nashorn', make 8 tests fails. Javascript code generated is the same, and the javascript code is correct, works perfectly in Node.js. So is a 'nashorn' problem. I think Oracle is working to improve it, but I don't know if they will fix it or not.

So, we can ignore that tests in Java 8, or you guys use Java 7 to test or build the project :)

**Comment by abelsromero** [comment]
How about integrating TravisCI and AppVeyor to test the builds in Java 7 and 8 in linux and Windows?
Truth be told I have no experience with SnapCI and I ignore its options, but I've using the other services for some time and they work like a charm :+1: 

I already have the builds set in my fork https://github.com/abelsromero/grooscript. I can only send a PR with the configuration files, you'll have to enable them later, but it can be done in no time.

what do you think?

**Comment by chiquitinxx** [comment]
Sure, please do it!

**Comment by abelsromero** [comment]
I added the configuration files and I am able to set AppVeyor but not TravisCI, which is weird because I can manage other projects I have permisions on.
Anyway, can you go into https://travis-ci.org/ and enable the project?

**Comment by abelsromero** [comment]
I correct, I cannot set AppVeyour neither :%

**Comment by chiquitinxx** [comment]
I have created both, do you need any permissions or something?

**Comment by abelsromero** [comment]
Right not just by pushing the confif files anyone can play with it now. Now it's time to fix the issues :+1:

**Comment by chiquitinxx** [comment]
Like almost all tests runs in java javascript engine, and in Node.js. I think no bad solution, is to ignore, in that 8 tests, the java engine execution. Still Node.js will test it.

**Comment by chiquitinxx** [comment]
Fixed, now works in Java8, and build in Travis CI.
