### ISSUE TITLE
AppVeyour build fails while executing 'npmInstall'

### ISSUE THREAD

**Issue by abelsromero** [chiquitinxx/grooscript#29]
Even on Java7 build failds for some unknown reason while installing npm ([see] (https://ci.appveyor.com/project/chiquitinxx/grooscript/build/job/nal7957si98x9ttu)).

Alternatives 'in the works' are installing npm with chocolately, see:
. Chocolately in AppVeyor: http://www.appveyor.com/docs/build-configuration#installing-software
. Chocolately npm package: https://chocolatey.org/packages/npm)

**Comment by chiquitinxx** [comment]
No idea, maybe you can try with other Node.js versions.

**Comment by abelsromero** [comment]
This PR fixes the execution in AppVeyor.

On a side note :open_mouth:, github monitors every commit, only last one is correct.
