### ISSUE TITLE
Some tests fail on Windows

### ISSUE THREAD

**Issue by abelsromero** [chiquitinxx/grooscript#32]
It seems there's some platform dependant issue that makes that generated JS contains Windows line breaks (`\r\n`) when working on Windows7 and Windows Azure in AppVeyour (other Windows version not tested).

Here is an example of test org.grooscript.*GrooScriptSpec* -> *convert to groovy generates js code*
```
Condition not satisfied:

GrooScript.convert(code) == 'gs.toGroovy("hello");\n'
           |       |     |
           |       |     false
           |       |     1 difference (95% similarity)
           |       |     gs.toGroovy("hello");(\r)\n
           |       |     gs.toGroovy("hello");(-~)\n
           |        
           |       import static org.grooscript.GrooScript.toGroovy
           |        
           |       toGroovy('hello')
           gs.toGroovy("hello");

	at org.grooscript.GrooScriptSpec.convert to groovy generates js code(GrooScriptSpec.groovy:168)
```

**Comment by chiquitinxx** [comment]
I'll fix that

**Comment by chiquitinxx** [comment]
I have fixed a few, but for nexts, have to be done by a windows user. There is a problem with phantomjs, I think npm only installs a unix version, dunno where phantomjs.exe is. Also some issues with HttpServer of functional tests. Have tryed access resources files of the build, in AppVeyour, to see tests report, without success.

**Comment by abelsromero** [comment]
I'm wondering either if the best solution is replacing tests or making so that line breaks are always the same in all environments.

**Comment by chiquitinxx** [comment]
I have tried to setup appveyor.yml to do only unit tests, but seems is not working.

**Comment by abelsromero** [comment]
I'm working on a fix for it, so far is working on my local machine. I just pulled it a few minutes ago and I'm waiting for the AppVeyor build.
TravisCI gives OK :+1:

**Comment by abelsromero** [comment]
Fully closed with last PR. Now we have fully automatic testing on Linux and Windows.

**Comment by chiquitinxx** [comment]
Congratulations, good job :)
