### ISSUE TITLE
Multi-case switch statements not working

### ISSUE THREAD

**Issue by ruaanvds** [chiquitinxx/grooscript#59]
When running the following in the Groovy console, it returns **true**. 

```
def input = "image.jpg"
def parts = input.tokenize('.')
def ext = parts[parts.size() - 1]

switch (ext.toLowerCase()) {
    case 'jpg':
    case 'jpeg':
    case 'gif':
    case 'bmp':
    case 'png':
        //etc
        return true
}
return false
```

Yet, when running it in Grooscript, it returns **false**. 

Any pointers? Let me know if I should create a PR.

**Comment by chiquitinxx** [comment]
I'm happy if you want to fix it :) I was planning a release soon

**Comment by chiquitinxx** [comment]
I think is fixed :) Thanks again
