### ISSUE TITLE
node installation on PCF

### ISSUE THREAD

**Issue by ganeshwankhedkar** [chiquitinxx/grooscript#65]
we are actually trying to deploy angular project on PCF and which we have to deploy project using jenkins, we are able to push app on PCF but it fails due node installation taking too much time and getting terminated automatically.
can we have something else to achieve this task ?

**Comment by chiquitinxx** [comment]
I suppose you mean Pivotal Cloud Foundry. I have no idea about the problem.
I have checked 'npm install grooscript' works fine. Can you install other
npm packages? maybe PCF has a proxy or something? I think you better
contact PCF support to get more info :)
