### ISSUE TITLE
Is the project going to be maintained or is it dead?

### ISSUE THREAD

**Issue by vherasme** [chiquitinxx/grooscript#66]
Hello. I learned Groovy about a year ago and have been working with JS since 2015. Are you going to close and/or abandon the project? What do I need in order to collaborate? Kind regards,

Victor

**Comment by chiquitinxx** [comment]
Hello Victor! Agree not very active. I created a branch for starting support groovy 3, but not working on that. Sure you can contribute :) or you can be the new leader if you want. I'm more than happy to give you support, information or whatever you need

**Comment by vherasme** [comment]
Hello. Tell me where to start!

I would like to know:

- What level of knowledge is required, ie, how much of AST, compilers, etc I need to know? I am ready for all the suggestions you can give me. I can review material if neccesary.

- What tool / IDE do you recommend for working on this?

**Comment by chiquitinxx** [comment]
I use Intellij IDEA. There are a lot of tests in the project, I suggest you clone it, and see tests. Also take a look at project documentation, play with it, convert code, run converted code. The groovy code is converted to an AST tree and then generate javascript code from there. You can debug tests from IDE. Also take a look at grooscript.js the javascript library needed to run generated code, if you are familiar with javascript maybe can improve it.

**Comment by cdrchops** [comment]
let me know if you want help - I love this project.  I've been using it on my projects.  it makes writing my Groovy libraries with test code insanely easier to run tests and then convert it to use on my site.

**Comment by chiquitinxx** [comment]
Nice, thank you!

You are more than welcome to improve or continue grooscript. Just start to create issues with the stuff you want to do, and start to create PR's. I'm not developing grooscript at the moment, and no plans to continue, I'm happy to pass the project to another mantainer.

**Comment by cdrchops** [comment]
That sounds good to me.  Where is the groovy 3 progress at?  I'll work on getting it to build locally and start there.  thanks

**Comment by chiquitinxx** [comment]
There is a branch https://github.com/chiquitinxx/grooscript/tree/nextGrooscript. But I had some issues with Spock, and started to migrate the tests. So, maybe you can try to create a branch from master, upgrade dependencies to groovy 3 and new Spock 2, and see what's happening. Let me know if you have problems building or testing the project.

**Comment by chiquitinxx** [comment]
https://github.com/chiquitinxx/grooscript/issues/68
